version: 2.1
orbs:
  node: circleci/node@3.0.0
  browser-tools: circleci/browser-tools@1.1.0
jobs:
    test:
        docker:
          - image: cimg/node:lts-browsers
        steps:
          - checkout
          - node/install-packages
          - run:
              command: npm run test
          -store_test_results:
              path: /tmp/test-results
workflows:
  unit-tests:
    jobs:
      - test
