version: 2.1

jobs:
  web:
    docker:
      - image: circleci/node:12.13.0
    
    working_directory: ~/react-ecommerce-autoparts-template
    
    steps:
      - checkout
      - run: npm install
      # - run: npm run lint
      - run: npm run build
      - run: npm run test:coverage

workflows:
  version: 2
  concurrently:
    jobs:
      - web