version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:12.13.0
    working_directory: ~/react-ecommerce-autoparts-template
    steps:
      - checkout
      - run: npm install
      - run: echo "building your app now..."
      - run: npm run build

  # test:
  #   docker:
  #     - image: circleci/node:12.13.0
  #   working_directory: ~/react-ecommerce-autoparts-template
  #   steps:
  #     - checkout
  #     - run: echo "running your tests now..."
      # - run: npm run test

workflows:
  version: 2
  workflow:
    jobs:
      - build
      - test:
          require: build